# Site settings
title: Portfolio Website
description: My personal technical portfolio
#baseurl: "portfoliosite" # the subpath of your site, e.g. /blog
url: "/profile" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Varun Rustomji
user_description: Software Engineering Intership Portfolio.
user_title: Software Developer
email: vrustomj@sfu.ca
github_username:  VarunRustomji


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
